-- 00_init_schema.sql
-- Tiempos Pro Digital v4.0 - Initial Schema

-- 1. Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 2. App Users (Extends Supabase Auth)
CREATE TABLE IF NOT EXISTS public.app_users (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    auth_uid UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    cedula TEXT UNIQUE NOT NULL,
    email TEXT,
    phone TEXT UNIQUE NOT NULL,
    role TEXT NOT NULL CHECK (role IN ('SuperAdmin', 'Vendedor', 'Cliente')),
    balance_bigint BIGINT DEFAULT 0,
    currency TEXT DEFAULT 'CRC',
    status TEXT DEFAULT 'Active' CHECK (status IN ('Active', 'Suspended')),
    issuer_id UUID, -- Who created this user (for Vendedores/Clientes)
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Lottery Results (Draws)
CREATE TABLE IF NOT EXISTS public.lottery_results (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    date DATE NOT NULL,
    "drawTime" TEXT NOT NULL, -- Quoted to match TS property if needed, or snake_case mapped
    "winningNumber" TEXT,
    "isReventado" BOOLEAN DEFAULT FALSE,
    "reventadoNumber" TEXT,
    status TEXT DEFAULT 'OPEN' CHECK (status IN ('OPEN', 'CLOSED', 'VERIFYING')),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(date, "drawTime")
);

-- 4. Bets
CREATE TABLE IF NOT EXISTS public.bets (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    ticket_code TEXT NOT NULL,
    user_id UUID REFERENCES public.app_users(id),
    vendor_id UUID REFERENCES public.app_users(id),
    draw_id UUID REFERENCES public.lottery_results(id), -- Optional linkage
    amount_bigint BIGINT NOT NULL,
    numbers TEXT NOT NULL,
    status TEXT DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'WON', 'LOST', 'REFUNDED')),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Ledger Transactions (Double Entry)
CREATE TABLE IF NOT EXISTS public.ledger_transactions (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    ticket_code TEXT,
    user_id UUID REFERENCES public.app_users(id),
    amount_bigint BIGINT NOT NULL,
    balance_before BIGINT NOT NULL,
    balance_after BIGINT NOT NULL,
    type TEXT NOT NULL CHECK (type IN ('CREDIT', 'DEBIT', 'FEE', 'ADJUSTMENT', 'COMMISSION_PAYOUT')),
    reference_id TEXT,
    meta JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. Audit Trail
CREATE TABLE IF NOT EXISTS public.audit_trail (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id TEXT DEFAULT uuid_generate_v4()::text,
    timestamp TIMESTAMPTZ DEFAULT NOW(),
    actor_id UUID, -- Nullable for system events
    actor_role TEXT,
    actor_name TEXT,
    ip_address TEXT,
    device_fingerprint TEXT,
    type TEXT NOT NULL,
    action TEXT NOT NULL,
    severity TEXT NOT NULL,
    target_resource TEXT,
    metadata JSONB DEFAULT '{}'::jsonb,
    hash TEXT -- For integrity
);

-- Indexes for Performance
CREATE INDEX IF NOT EXISTS idx_app_users_auth_uid ON public.app_users(auth_uid);
CREATE INDEX IF NOT EXISTS idx_bets_user_id ON public.bets(user_id);
CREATE INDEX IF NOT EXISTS idx_ledger_user_id ON public.ledger_transactions(user_id);
